import 'package:flutter_test/flutter_test.dart';
import 'package:video_player_app/features/youtube_download/services/yt_dlp_meta_parser.dart';

void main() {
  group('YtDlpMetaParser', () {
    const parser = YtDlpMetaParser();

    test('parses structured metadata and filters storyboard formats', () {
      final meta = parser.parse({
        'id': 'abc123',
        'extractor_key': 'Youtube',
        'webpage_url': 'https://www.youtube.com/watch?v=abc123',
        'title': 'Parser Test',
        'uploader': 'Uploader',
        'duration': 95,
        'thumbnail': 'https://example.com/fallback.jpg',
        'thumbnails': [
          {'url': 'https://example.com/small.jpg', 'width': 120, 'height': 90},
          {
            'url': 'https://example.com/large.jpg',
            'width': 1280,
            'height': 720,
          },
        ],
        'formats': [
          {
            'format_id': 'sb0',
            'ext': 'mhtml',
            'format_note': 'storyboard',
            'vcodec': 'none',
            'acodec': 'none',
          },
          {
            'format_id': '137',
            'ext': 'mp4',
            'vcodec': 'avc1.640028',
            'acodec': 'none',
            'width': 1920,
            'height': 1080,
            'fps': 30,
            'tbr': 4500,
          },
          {
            'format_id': '140',
            'ext': 'm4a',
            'vcodec': 'none',
            'acodec': 'mp4a.40.2',
            'abr': 128,
            'asr': 44100,
            'language': 'zh-CN',
            'language_preference': 10,
          },
        ],
        'subtitles': {
          'zh-CN': [
            {'ext': 'vtt'},
            {'ext': 'srt'},
          ],
        },
        'automatic_captions': {
          'en': [
            {'ext': 'vtt'},
          ],
        },
        'chapters': [
          {'title': 'Intro', 'start_time': 0, 'end_time': 12.5},
        ],
      });

      expect(meta.source, 'youtube');
      expect(meta.bestThumbnailUrl, 'https://example.com/large.jpg');
      expect(meta.videoFormats, hasLength(1));
      expect(meta.audioFormats, hasLength(1));
      expect(meta.videoFormats.first.displayLabel, contains('1080p'));
      expect(meta.audioFormats.first.language, 'zh-CN');
      expect(meta.subtitles, hasLength(2));
      expect(meta.subtitles.first.languageCode, 'zh-CN');
      expect(meta.subtitles.last.isAutoGenerated, isTrue);
      expect(meta.chapters.single.title, 'Intro');
      expect(meta.videoFormatGroups['1080p'], ['137']);
      expect(meta.audioFormatGroups['zh-CN'], ['140']);
      expect(meta.recommendedVideoFormatId, '137');
      expect(meta.recommendedAudioFormatId, '140');
      expect(meta.recommendedSubtitleLanguages, ['zh-CN']);
      expect(meta.rawInfo['id'], 'abc123');
    });

    test('infers codec and keeps unknown file sizes as null', () {
      final meta = parser.parse({
        'id': 'short-1',
        'extractor': 'youtube',
        'original_url': 'https://youtu.be/demo',
        'title': 'Shorts',
        'channel': 'Demo Channel',
        'formats': [
          {
            'format_id': '18',
            'ext': 'mp4',
            'format': '360p h264',
            'format_note': '360p',
            'vcodec': 'unknown',
            'acodec': 'aac',
            'height': 360,
          },
          {
            'format_id': '251',
            'ext': 'webm',
            'vcodec': 'none',
            'acodec': 'opus',
            'format': 'audio only opus',
            'filesize': null,
          },
        ],
      });

      expect(meta.videoFormats.single.videoCodec, 'unknown');
      expect(meta.videoFormats.single.hasAudio, isTrue);
      expect(meta.audioFormats.single.audioCodec, 'opus');
      expect(meta.audioFormats.single.fileSize, isNull);
      expect(meta.recommendedVideoFormatId, '18');
      expect(meta.recommendedAudioFormatId, '251');
    });

    test('sorts shorts by quality but recommends compatible h264', () {
      final meta = parser.parse({
        'id': 'shorts-demo',
        'extractor_key': 'YoutubeShorts',
        'webpage_url': 'https://www.youtube.com/shorts/demo',
        'title': 'Short Demo',
        'uploader': 'Short Channel',
        'formats': [
          {
            'format_id': '401',
            'ext': 'mp4',
            'vcodec': 'av01.0.08M.08',
            'acodec': 'none',
            'height': 1080,
            'tbr': 2200,
          },
          {
            'format_id': '18',
            'ext': 'mp4',
            'vcodec': 'avc1.42001E',
            'acodec': 'mp4a.40.2',
            'height': 360,
            'tbr': 900,
          },
          {
            'format_id': '22',
            'ext': 'mp4',
            'vcodec': 'avc1.64001F',
            'acodec': 'mp4a.40.2',
            'height': 720,
            'tbr': 1600,
          },
        ],
      });

      expect(meta.source, 'youtube');
      expect(meta.videoFormats.first.formatId, '401');
      expect(meta.recommendedVideoFormatId, '22');
      expect(meta.videoFormatGroups['720p'], contains('22'));
    });

    test('keeps manual subtitles ahead of automatic subtitles', () {
      final meta = parser.parse({
        'id': 'sub-demo',
        'extractor_key': 'Youtube',
        'webpage_url': 'https://www.youtube.com/watch?v=sub-demo',
        'title': 'Subtitle Demo',
        'uploader': 'Subtitle Channel',
        'formats': [
          {
            'format_id': '18',
            'ext': 'mp4',
            'vcodec': 'avc1.42001E',
            'acodec': 'mp4a.40.2',
            'height': 360,
          },
        ],
        'subtitles': {
          'ja': [
            {'ext': 'vtt'},
          ],
          'en': [
            {'ext': 'srt'},
          ],
        },
        'automatic_captions': {
          'en': [
            {'ext': 'vtt'},
          ],
        },
      });

      expect(meta.subtitles.first.isAutoGenerated, isFalse);
      expect(meta.recommendedSubtitleLanguages, ['en']);
    });

    test(
      'does not auto-select subtitle when only automatic captions exist',
      () {
        final meta = parser.parse({
          'id': 'auto-only',
          'extractor_key': 'Youtube',
          'webpage_url': 'https://www.youtube.com/watch?v=auto-only',
          'title': 'Auto Subtitle Only',
          'uploader': 'Auto Channel',
          'formats': [
            {
              'format_id': '140',
              'ext': 'm4a',
              'vcodec': 'none',
              'acodec': 'mp4a.40.2',
              'abr': 128,
            },
          ],
          'automatic_captions': {
            'en': [
              {'ext': 'vtt'},
            ],
            'zh-CN': [
              {'ext': 'srv3'},
            ],
          },
        });

        expect(meta.audioFormats.single.formatId, '140');
        expect(meta.subtitles, hasLength(2));
        expect(meta.subtitles.every((item) => item.isAutoGenerated), isTrue);
        expect(meta.recommendedSubtitleLanguages, isEmpty);
      },
    );

    test(
      'subtitle labels normalize odd automatic caption language codes and prioritize chinese and english',
      () {
        final meta = parser.parse({
          'id': 'auto-multi',
          'extractor_key': 'Youtube',
          'webpage_url': 'https://www.youtube.com/watch?v=auto-multi',
          'title': 'Auto Multi',
          'uploader': 'Auto Multi Channel',
          'formats': [
            {
              'format_id': '18',
              'ext': 'mp4',
              'vcodec': 'avc1.42001E',
              'acodec': 'mp4a.40.2',
              'height': 360,
            },
          ],
          'subtitles': {
            'zh-Hans': [
              {'ext': 'srt'},
            ],
          },
          'automatic_captions': {
            'en-US-cvfXDfbeED0': [
              {'ext': 'srv3'},
            ],
            'aa': [
              {'ext': 'srv3'},
            ],
            'ab': [
              {'ext': 'srv3'},
            ],
          },
        });

        expect(meta.subtitles.first.displayName, '中文(简体)');
        expect(meta.subtitles[1].displayName, 'English (US) (自动)');
        expect(
          meta.subtitles.any((item) => item.displayName == 'Afar (自动)'),
          isTrue,
        );
        expect(
          meta.subtitles.any((item) => item.displayName == 'Abkhazian (自动)'),
          isTrue,
        );
      },
    );
  });
}
