import 'dart:convert';
import 'dart:developer' as developer;

class SubtitleUtil {
  static const Map<String, String> _lanMap = {
    "ai-Zh": "中文（简体, AI识别）",
    "ai-En": "English(generated by ai)",
    "zh-CN": "中文（简体）",
    "zh-HK": "中文（香港繁體）",
    "zh-Hans": "中文（简体）",
    "zh-TW": "中文（台灣繁體）",
    "zh-Hant": "中文（繁體）",
    "en-US": "English(USA)",
    "ja": "日本語",
    "ko": "한국어",
    "zh-SG": "中文（新加坡）",
    "ab": "Аҳәынҭқарра",
    "aa": "Qafár af",
    "af": "Afrikaans",
    "sq": "Gjuha shqipe",
    "ase": "American Sign Language",
    "am": "አማርኛ",
    "arc": "ܐܪܡܝܐ",
    "hy": "հայերեն",
    "as": "অসমীয়া",
    "ay": "Aymar aru",
    "az": "Azərbaycan",
    "bn": "বাংলা ভাষার",
    "ba": "Башҡорттеле",
    "eu": "Euskara",
    "be": "беларуская мова biełaruskaja mova",
    "bh": "Bihar",
    "bi": "Bislama",
    "bs": "босански",
    "br": "Breton",
    "bg": "български",
    "yue": "粵語",
    "yue-HK": "粵語（中國香港）",
    "ca": "català",
    "chr": "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ",
    "cho": "Chahta'",
    "co": "lingua corsa",
    "hr": "Hrvatska",
    "cs": "čeština",
    "da": "Dansk",
    "nl": "Nederlands",
    "nl-BE": "Nederlands(Belgisch)",
    "nl-NL": "Nederlands(Nederlands)",
    "dz": "རྫོང་ཁ།",
    "en": "English",
    "en-CA": "English(Canada)",
    "en-IE": "English(Ireland)",
    "en-GB": "English(UK)",
    "eo": "Esperanto",
    "et": "Eestlane",
    "fo": "føroyskt",
    "fj": "Vakaviti",
    "fil": "Pilipino",
    "fi": "Suomi",
    "fr": "Français",
    "fr-BE": "Français(Belgique)",
    "fr-CA": "Français(Canada)",
    "fr-FR": "Français(La France)",
    "fr-CH": "Français(Suisse)",
    "ff": "Fulani",
    "gl": "galego",
    "ka": "ქართული ენა",
    "de": "Deutsch",
    "de-AT": "Deutsch(Österreich)",
    "de-DE": "Deutsch(Deutschland)",
    "de-CH": "Deutsch(Schweiz)",
    "el": "Ελληνικά",
    "kl": "Kalaallisut",
    "gn": "avañe'ẽ",
    "gu": "ગુજરાતી",
    "hak": "Hak-kâ-fa",
    "hak-TW": "Hak-kâ-fa",
    "ha": "هَوُسَ",
    "iw": "שפה עברית",
    "hi": "हिन्दी",
    "hi-Latn": "हिंदी(फोनेटिक)",
    "hu": "Magyar",
    "is": "icelandic",
    "ig": "Asụsụ Igbo",
    "id": "Bahasa Indonesia", // Or "Indonesia" per BBDown
    "ia": "Interlingua",
    "iu": "ᐃᓄᒃᑎᑐᑦ",
    "ik": "Inupiat",
    "ga": "Gaeilge na hÉireann",
    "it": "Italiano",
    "jv": "ꦧꦱꦗꦮ",
    "kn": "ಕನ್ನಡ",
    "ks": "कॉशुर",
    "kk": "Қазақ тілі",
    "km": "ភាសាខ្មែរ",
    "rw": "Ikinyarwanda",
    "tlh": "tlhIngan Hol",
    "ku": "Kurdî",
    "ky": "кыргыз тили",
    "lo": "ພາສາລາວ",
    "la": "latīna",
    "lv": "latviešu valoda",
    "ln": "Lingála",
    "lt": "lietuvių kalba",
    "lb": "Lëtzebuergesch",
    "mk": "Македонски јазик",
    "mg": "maa.laa.gaas",
    "ms": "Melayu",
    "ml": "മലയാളം",
    "mt": "Lingwa Maltija",
    "mi": "Māori",
    "mr": "मराठी Marāṭhī",
    "mas": "Maasai",
    "nan": "閩南語",
    "nan-TW": "閩南語(台灣)",
    "lus": "Mizo ṭawng",
    "mo": "Limba moldovenească",
    "mn": "монгол хэл",
    "my": "မြန်မာဘာသာ",
    "na": "Dorerin Naoero",
    "nv": "Diné bizaad",
    "ne": "नेपाली Nepālī",
    "no": "norsk språk",
    "fa": "فارسی",
    "fa-AF": "فارسی",
    "fa-IR": "فارسی",
    "pl": "Polski",
    "pt": "Português",
    "pt-BR": "Português(brasil)",
    "pt-PT": "Português(portugal)",
    "ro": "Română",
    "ru": "Русский",
    "ru-Latn": "Русский(фонетический)",
    "sr": "Српски",
    "sr-Cyrl": "Српски(ћирилица)",
    "sr-Latn": "Српски(латиница)",
    "sh": "srpskohrvatski",
    "sk": "slovenský",
    "es": "Español",
    "es-419": "Español(Latinoamérica)",
    "es-MX": "Español(México)",
    "es-ES": "Español(España)",
    "es-US": "Español(Estados Unidos)",
    "sv": "Svenska",
    "tl": "Tagalog",
    "th": "ไทย",
    "tr": "Türkçe",
    "uk": "Українська",
    "ur": "Urdu",
    "vi": "Tiếng Việt",
  };

  static String getLanguageName(String key) {
    if (key.startsWith("ai-")) {
      final baseKey = key.substring(3);
      final baseName = _lanMap[baseKey] ?? _lanMap[baseKey.toLowerCase()] ?? baseKey;
      return "$baseName (AI识别)";
    }
    return _lanMap[key] ?? _lanMap[key.toLowerCase()] ?? key;
  }

  static String convertJsonToSrt(dynamic jsonContent) {
    final buffer = StringBuffer();
    try {
      dynamic json;
      if (jsonContent is String) {
        json = jsonDecode(jsonContent);
      } else {
        json = jsonContent;
      }

      if (json == null || json['body'] == null) return "";

      final body = json['body'] as List;
      
      for (int i = 0; i < body.length; i++) {
        final item = body[i];
        final from = (item['from'] as num?)?.toDouble() ?? 0.0;
        final to = (item['to'] as num?)?.toDouble() ?? 0.0;
        final content = item['content'] as String? ?? "";
        
        buffer.writeln((i + 1).toString());
        buffer.writeln("${formatTime(from)} --> ${formatTime(to)}");
        buffer.writeln(content);
        buffer.writeln(); // Blank line
      }
    } catch (e) {
      developer.log('Error converting subtitle', error: e);
      return "";
    }
    return buffer.toString();
  }

  static String formatTime(double seconds) {
    final duration = Duration(milliseconds: (seconds * 1000).round());
    final h = duration.inHours.toString().padLeft(2, '0');
    final m = (duration.inMinutes % 60).toString().padLeft(2, '0');
    final s = (duration.inSeconds % 60).toString().padLeft(2, '0');
    final ms = (duration.inMilliseconds % 1000).toString().padLeft(3, '0');
    return "$h:$m:$s,$ms";
  }
}
